<?PHP

/**
*
*   Contábil WEB
*
*   Data de Criacao: 26/05/2003
*   Ultima Atualizacao: 26/05/2003
*   Modulo: cwLogin.inc
*
*   Desenvolvido por APOENA Solucoes em Software Livre
*   suporte@apoenasoftwarelivre.com.br
*   http://www.apoenasoftwarelivre.com.br
*
*   @author     Claudimir Zavalik (claudimir@apoenasoftwarelivre.com.br)
*   @author     Guilherme Silva de Lacerda (guilherme@apoenasoftwarelivre.com.br)
*   @version    PHP3 & PHP4
*/

$pathClasses = "./classes/";

// Dicionario I18N
include_once $pathClasses."MessageBundle.properties";

?>
